### ISSUE TITLE
We have different possible architectures...

### ISSUE THREAD

**Issue by deca12x** [bangtam1994/Re-sell-dapp#15]
**### Event ticketing dapp with logic for reselling**
 
Decision a) Ticekts are NFTs. ERC 721 or ERC1155?
- Option a) ERC721 would allow for e.g. buying a specific row and seat no. Better UX, but would present the following difficulties: The UI will allow the user to select e.g. Seat A27 - but how would they know if that seat is available or not. We would have to display info about which seats are available in the frontend in a nice way, which would add to our already large scope of work for just 3 evenings. 
- Option b) ERC1155 would be only for e.g. standing, seated or VIP. Not as good UX, but still that's how many events work (e.g. any events on Dice or ResidentAdvisor in London). Less work, but still we need to implement logic in the frontend to let the user create an event with multiple ticketing options, not knowing how many they'll want to add.
- Option c) We allow the user to buy a single type of ticket (no seat number, no seat type). Super simple, quick proof of concept. This is the least complex but could still be better UX than if we had uncurated frontend of more time-consuming options. If we do this, then it would be best to use ERC721, as ERC1155 necessarily requires the URI with metadata, wheras ERC721 doesn't.
 
Decision b) 1 or 2 Contracts?
- Option a) A single Event.sol contract that inherits ERC?? and then gets deployed for each new event. All methods are in this single contract.
- Option b) A central contract with most needed methods gets deployed by us a single time. A second contract gets deployed each time a user wants to create a new event.

Decision c) Who deploys?
- Option a) the event contract is deployed by the user/event organiser direct from frontend (Scaffold) with user signature. This approach offers the advantages of being a direct call frontend to blockchain, and that the msg.sender is contract owner. However if the user were to close a tab, react would not get a chance to get the contract address returned, and therefore it wouldn't be stored in the backend Mongodb.
- Option b) the event contract is deployed by the dApp developer in the backend from Nestjs. The advantage is that we make it atomic, fixing the issues above. The first disadvantage would be that we can't pass the user's address to the constructor with msg.sender. Instead, we could get the user's address with a wagmi hook, then send to the backend with a dto, then used by the backend as an argument when deploying the contract. So that one is not a problem. The second disadvantage would be that the dapp developer would be paying for deployment every time a user creates an event. This could be a big attack vector.

**Comment by MatheusDaros** [comment]
Hello @deca12x 

Thanks for opening this issue.

> Decision a)

Please provide me some more info on why would you consider using `ERC1155`
By the seems of it, you have a link of `1:1` from NFT to Asset (ticket)
The `ERC1155` would enable you doing a `1:N` link, and also batch mints, transfers and etc. Is that what you need?

> Decision b) 

Dividing contracts is much better for composability and maintenability. The downside would be a bit more of gas costs due to external calls.
Evaluate this with care depending on your planned features to guarantee that you're not going to have problems down the road.

> Decision c)

By the way I see, you can have both ways working side by side. Option `b)` would incur a lot of gas costs on you, so perhaps this is not something that would be financially sustainable unless you charge for it somehow.

**Comment by deca12x** [comment]
- We will have a single ticket type, using ERC721
- We only have 1 contract Event.sol
- We are deploying each event from the frontend
